tab_spaces = 2
max_width = 80
reorder_imports = true
newline_style = "Unix"
fn_params_layout = "Vertical"
match_block_trailing_comma = true
struct_lit_width = 0
struct_variant_width = 0
use_try_shorthand = true


unstable_features = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
#brace_style = "AlwaysNextLine"
#normalize_doc_attributes = true
#wrap_comments = true
#format_code_in_doc_comments = true
#struct_lit_single_line = false
#normalize_comments = true
#format_strings = true
#imports_layout = "Vertical"
#imports_granularity = "Item"
#group_imports = "StdExternalCrate"
#reorder_impl_items = true
#struct_field_align_threshold = 20
#condense_wildcard_suffixes = true

