[package]
name = "meritrank"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "meritrank"
path = "src/main.rs"

#[[test]]
#name = "test_randomwalk"
#path = "tests/*"

[lib]
name = "meritrank"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "0.8"
petgraph = "0.5"
uuid = "1.3.3"
indexmap = "1.8.0"
fixedbitset = "0.2.0"
once_cell = "1.8.0"
ordered-float = "1.0"
num-traits = "0.2.14"
