[package]
name = "pgmer2"
version = "0.3.19"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg16"]
shared = []
pg16 = ["pgrx/pg16", "pgrx-tests/pg16"]
pg_test = []

[dependencies]
meritrank_service = { path="../service" }

pgrx = "0.11.4"
nng = "1.0.1"
rmp-serde = "1.1.2"
serde = "1.0.193"
lazy_static = "1.4"

dotenv = { version = "0.15.0" }

[dev-dependencies]
pgrx-tests = "=0.11.4"
