FROM postgres:17-alpine

RUN apk add git rust cargo rustfmt jq cmake make gcc clang21 clang21-libclang musl-dev openssl-dev postgresql17-dev jq

ENV RUSTFLAGS="-Ctarget-feature=-crt-static"
ENV LIBCLANG_PATH=/usr/lib/llvm21/lib

RUN cargo install --locked --version 0.17.0 cargo-pgrx
ENV PATH="/root/.cargo/bin:$PATH"
RUN cargo pgrx init --pg17 pg_config
