[package]
name = "meritrank_service"
version = "0.2.51"
edition = "2021"

[features]
shared = []

[dependencies]
meritrank_core = { path = "../core" }

petgraph = "0.6.3"
serde = "1.0.166"

nng = "1.0.1"
rmp-serde = "1.1.2"
simple-pagerank = "0.2.0"

ctrlc = "3.4.4"
chrono = "0.4.38"
once_cell = "1.20.1"
lru = "0.12.5"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
