name: Build and test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch: 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo build
    - name: Run tests
      run: |
        cargo test -- --skip smoke_memory
  memory_consumption:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and run the test
      run: |
        export MERITRANK_NO_ASSERT=1
        export MEM_KB=`/usr/bin/time -f "%M" cargo test smoke_memory --release --quiet 2>&1 1>/dev/null`
        echo "Memory consumption is $MEM_KB KB"
        if [ $MEM_KB -gt 550000 ]; then
          exit 1
        fi
