name: Build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  test_core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo build
    - name: Run tests
      run: |
        cargo test -- --skip smoke_memory
  test_memory_consumption:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v4
    - name: Build and run the test
      run: |
        export MERITRANK_NO_ASSERT=1
        export MEM_KB=`/usr/bin/time -f "%M" cargo test smoke_memory --release --quiet 2>&1 1>/dev/null`
        echo "Memory consumption is $MEM_KB KB"
        if [ $MEM_KB -gt 550000 ]; then
          exit 1
        fi
  test_service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: |
        export MERITRANK_NUM_WALK=50
        cargo test
  # TODO: Add Redis FDW integration tests.
  test_docker_service:
    needs: [ test_core, test_memory_consumption, test_service ]
    if: success()
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: |
        docker build -f ./Dockerfile ..
  test_docker_postgres:
    needs: [ test_core, test_memory_consumption, test_service ]
    if: success()
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./postgres
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: |
        docker build -f ./Dockerfile ..
