name: Publish
on:
  workflow_dispatch: 
jobs:
  test_core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        cargo test -- --skip smoke_memory
  test_service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        export MERITRANK_NUM_WALK=50
        cargo test
  publish_service:
    needs: [ test_core, test_service ]
    if: success()
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service
    steps:
    - uses: actions/checkout@v4
    - name: Check version
      id: check_version
      shell: bash
      run: |
        export VER=$(cargo metadata --format-version=1 | jq -r '.packages[] | select(.name=="meritrank_service") | .version')
        echo "VER=$VER"
        if ! [[ "$VER" =~ ^[0-9\.]+$ ]]; then
          echo "IGNORE DEV VERSION"
          echo "SKIP=1" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        if [ $(docker manifest inspect vbulavintsev/meritrank-service:v$VER >/dev/null 2>&1; echo $?) -eq 0 ]; then
          echo "ALREADY PUBLISHED"
          echo "SKIP=1" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        echo "SKIP=0"    >> "$GITHUB_OUTPUT"
        echo "TAG=v$VER" >> "$GITHUB_ENV"
    - name: Build docker image
      if: ${{ steps.check_version.outputs.SKIP == 0 }}
      run: |
        docker build -t vbulavintsev/meritrank-service:$TAG -f ./Dockerfile ..
    - name: Push docker image to Dockerhub
      if: ${{ steps.check_version.outputs.SKIP == 0 }}
      shell: bash
      run: |
        docker login -u vbulavintsev -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker image push vbulavintsev/meritrank-service:$TAG
  publish_postgres:
    needs: [ test_core, test_service ]
    if: success()
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./postgres
    steps:
    - uses: actions/checkout@v4
    - name: Check version
      id: check_version
      shell: bash
      run: |
        export VER=0.4.1
        echo "VER=$VER"
        if ! [[ "$VER" =~ ^[0-9\.]+$ ]]; then
          echo "IGNORE DEV VERSION"
          echo "SKIP=1" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        if [ $(docker manifest inspect vbulavintsev/postgres-tentura:v$VER >/dev/null 2>&1; echo $?) -eq 0 ]; then
          echo "ALREADY PUBLISHED"
          echo "SKIP=1" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        echo "SKIP=0" >> "$GITHUB_OUTPUT"
        echo "TAG=v$VER" >> "$GITHUB_ENV"
    - name: Build docker image
      if: ${{ steps.check_version.outputs.SKIP == 0 }}
      run: |
        docker build -t vbulavintsev/postgres-tentura:$TAG -f ./Dockerfile ..
    - name: Push docker image to Dockerhub
      if: ${{ steps.check_version.outputs.SKIP == 0 }}
      shell: bash
      run: |
        docker login -u vbulavintsev -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker image push vbulavintsev/postgres-tentura:$TAG
